### ISSUE TITLE
How to integrate into LinearSolve.jl

### ISSUE THREAD

**Issue by PetrKryslUCSD** [PetrKryslUCSD/Sparspak.jl#2]
https://github.com/SciML/LinearSolve.jl

**Comment by Wimmerer** [comment]
Can we add a constructor that for `Problem` that takes `A`, `x` and `b` (`Ax = b`) Vectors as input?

**Comment by j-fu** [comment]
#9 could help with that.

**Comment by Wimmerer** [comment]
Okay great.

Now is there a way to pass a new vector of values for re-solving? After the symbolic factorization.

I see that `solve!` might be able to do this, but I'm not sure how to pass the new value vector in (we assume the pattern is the same of course).

**Comment by j-fu** [comment]
Here is what I did for ExtendableSparse.jl:
https://github.com/j-fu/ExtendableSparse.jl/blob/master/src/SparspakCSCInterface.jl


(BTW want to make that compatible to LinearSolve, but need to find the time...)

**Comment by PetrKryslUCSD** [comment]
> Okay great.
> 
> Now is there a way to pass a new vector of values for re-solving? After the symbolic factorization.
> 
> I see that `solve!` might be able to do this, but I'm not sure how to pass the new value vector in (we assume the pattern is the same of course).

If you'd like to use multiple right hand sides, use
```
zerorhs!(p)
infullrhs!(p, rhs)
```
This will be in the version 0.3.2 (just registered).

**Comment by PetrKryslUCSD** [comment]
I agree that integration into LinearSolve is probably the way to go to provide a really simple interface.

**Comment by Wimmerer** [comment]
@j-fu do you mind if I add that module from ExtendableSparse.jl to LinearSolve.jl?

**Comment by j-fu** [comment]
Since 0.33.1, Sparspak appears to be fully functional with LinearSolve. 
It is also the default solver for Non-GPL builds and general number types.

So I guess we can close this issue...
