### ISSUE TITLE
Gaussian elimination with partial pivoting using GPSolver

### ISSUE THREAD

**Issue by rwl** [PetrKryslUCSD/Sparspak.jl#26]
The User Guide mentions several different solvers:

> EnvSolver, EnvSpdSolver, SparseSolver, SparseSpdSolver, GPSolver, KdeltaSolver, and CLLSSolver

Do you have the Fortran 90 code for GPSolver? I have been working on a translation of Gilbert and Peierls original Fortran code to Rust.

https://github.com/rwl/rlu

Unfortunately, the performance doesn't match that of KLU. It would be interesting to read George and Liu's implementation and see if there are any improvements I can make.

**Comment by PetrKryslUCSD** [comment]
I don't, sorry. It was not part of the sources I got from George.
