### ISSUE TITLE
Julia 1.6

### ISSUE THREAD

**Issue by j-fu** [PetrKryslUCSD/Sparspak.jl#5]
Hi, is there any reason for not supporting Julia 1.6 (as it is designated as LTS version) ?

**Comment by PetrKryslUCSD** [comment]
It was simply to limit the necessary variety of manifests. Julia complained with one version about the manifest generated with another.

**Comment by j-fu** [comment]
I see, indeed there was an annoying and under-announced manifest format upgrade between 1.6 and 1.7. 

However for package CI I don't care that much - I develop und test on my computer on 1.8 and let the github CI figure out if things still run on 1.6 - the Manifest is not checked in. So usually have github CI running for 1.6, 1 (latest stable) and nightly...

It is more complicated with Pluto notebooks which contain manifests.

**Comment by PetrKryslUCSD** [comment]
Actually, there is much weightier reason: `libblastrampoline` is used, which the version 1.6 does not recognize.

**Comment by j-fu** [comment]
> Actually, there is much weightier reason: `libblastrampoline` is used, which the version 1.6 does not recognize.

Ah ok this is certainly a good reason.

**Comment by PetrKryslUCSD** [comment]
Julia 1.6 is now enabled by configuration of the BLAS routines during compilation.
The parametrization of the integer type is still looking for a solution.
